
db:
  jena:
    dir: /Users/javierflores/Documents/UPC_projects/new/newODIN/api
    name: jena2
  files:
    upload:
      dir: /Users/javierflores/Documents/UPC_projects/new/newODIN/api/uploads

logging:
  level:
    org.springframework.web: INFO
    edu.upc.essi.dtim.metadatastorage: DEBUG
