

db:
  jena:
    dir: /Users/javierflores/Documents/UPC Projects/2/newODIN/api
    name: jena2



spring:
  devtools:
    add-properties:false

logging:
  level:
    org.springframework.web: INFO
    edu.upc.essi.dtim.metadatastorage: INFO
