db:
  jena:
    dir: /home/metabig/Work/newODIN/api
    name: jena2
  files:
    upload:
      dir: /uploads


logging:
  level:
    org.springframework.web: INFO
    edu.upc.essi.dtim.metadatastorage: DEBUG
