
dataStorage:
  landingZone:
    dir: /Users/javierflores/Documents/upc/projects/newODIN/api/landing_zone

logging:
  level:
    org.springframework.web: INFO
    edu.upc.essi.dtim.metadatastorage: DEBUG